// src/agents/notificationAgent.js
// Agent 7 — Notification & Record Storage
// Stores ARN + PDF to Google Drive (user's own account).
// Sends push notification. Schedules next due-date reminder.
// All data stays in the user's own Google Drive — no Anthropic/app servers.

import * as Notifications from 'expo-notifications';
import * as FileSystem from 'expo-file-system';
import AsyncStorage from '@react-native-async-storage/async-storage';
import dayjs from 'dayjs';
import { GDRIVE_FOLDER_NAME, FILING_TYPES } from '../constants/gst';
import { getDriveService } from '../services/googleDriveService';

// ─────────────────────────────────────────────
// Push notification setup
// ─────────────────────────────────────────────

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: true,
  }),
});

export async function requestNotificationPermission() {
  const { status } = await Notifications.requestPermissionsAsync();
  return status === 'granted';
}

async function sendPushNotification(title, body, data = {}) {
  await Notifications.scheduleNotificationAsync({
    content: { title, body, data, sound: false },
    trigger: null, // immediate
  });
}

// ─────────────────────────────────────────────
// Due-date reminder scheduling
// ─────────────────────────────────────────────

export async function scheduleDueDateReminder(returnType, period, filingFrequency) {
  const cfg = FILING_TYPES[returnType]?.dueDates;
  if (!cfg) return;

  const day = filingFrequency === 'quarterly' ? (cfg.quarterly ?? cfg.monthly) : cfg.monthly;
  const dueDate = dayjs().month(period.month).year(period.year).date(day);
  const reminderDate = dueDate.subtract(3, 'day').hour(9).minute(0).second(0);

  if (reminderDate.isBefore(dayjs())) return; // past — skip

  const existingId = await AsyncStorage.getItem(`reminder_${returnType}_${period.year}_${period.month}`);
  if (existingId) await Notifications.cancelScheduledNotificationAsync(existingId).catch(() => {});

  const id = await Notifications.scheduleNotificationAsync({
    content: {
      title: `${returnType} due in 3 days`,
      body: `Your ${returnType} for ${period.label} is due on ${dueDate.format('DD MMM YYYY')}. Open the app to file.`,
      data: { returnType, period },
      sound: false,
    },
    trigger: { date: reminderDate.toDate() },
  });

  await AsyncStorage.setItem(`reminder_${returnType}_${period.year}_${period.month}`, id);
  return id;
}

// ─────────────────────────────────────────────
// Receipt PDF generation (minimal, on-device)
// ─────────────────────────────────────────────

export function buildReceiptHTML(filingResult, profile, period, summary) {
  const { arn, filedAt, returnType } = filingResult;
  const fmt = n => `₹${Number(n ?? 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>GST Filing Receipt</title>
<style>
  body{font-family:Arial,sans-serif;font-size:13px;color:#222;padding:24px}
  h2{color:#1a73e8;margin-bottom:4px}
  .meta{color:#666;font-size:11px;margin-bottom:16px}
  table{width:100%;border-collapse:collapse;margin-top:8px}
  th{background:#1a73e8;color:#fff;padding:6px 8px;text-align:left;font-size:12px}
  td{padding:5px 8px;border-bottom:1px solid #eee}
  .arn{font-size:15px;font-weight:bold;color:#0d7;background:#f0fff4;padding:10px;border-radius:4px;margin:12px 0}
  .footer{margin-top:20px;font-size:10px;color:#999}
</style>
</head>
<body>
<h2>GST Filing Acknowledgement</h2>
<div class="meta">Generated by GST Filing Agent · ${new Date(filedAt).toLocaleString('en-IN')}</div>
<table>
  <tr><th>Field</th><th>Details</th></tr>
  <tr><td>Business Name</td><td>${profile.tradeName}</td></tr>
  <tr><td>GSTIN</td><td>${profile.gstin}</td></tr>
  <tr><td>Return Type</td><td>${returnType}</td></tr>
  <tr><td>Filing Period</td><td>${period.label}</td></tr>
  <tr><td>Filed On</td><td>${new Date(filedAt).toLocaleDateString('en-IN')}</td></tr>
</table>
<div class="arn">ARN: ${arn}</div>
<table>
  <tr><th>Summary</th><th>Amount</th></tr>
  <tr><td>Total Taxable Value</td><td>${fmt(summary.totals.taxableValue)}</td></tr>
  <tr><td>CGST</td><td>${fmt(summary.totals.cgst)}</td></tr>
  <tr><td>SGST</td><td>${fmt(summary.totals.sgst)}</td></tr>
  <tr><td>IGST</td><td>${fmt(summary.totals.igst)}</td></tr>
  <tr><td><strong>Total Tax</strong></td><td><strong>${fmt(summary.totals.totalTax)}</strong></td></tr>
</table>
<div class="footer">This is a system-generated acknowledgement. Keep this for your records.</div>
</body>
</html>`;
}

// ─────────────────────────────────────────────
// Save to Google Drive
// ─────────────────────────────────────────────

async function saveToGoogleDrive(fileName, content, mimeType, drive) {
  try {
    const folder = await drive.getOrCreateFolder(GDRIVE_FOLDER_NAME);
    const fileId = await drive.uploadFile({
      name: fileName,
      mimeType,
      content,
      parentId: folder.id,
    });
    return { ok: true, fileId, driveUrl: `https://drive.google.com/file/d/${fileId}/view` };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

// ─────────────────────────────────────────────
// Save filing record to local storage (offline backup)
// ─────────────────────────────────────────────

async function saveLocalRecord(filingResult, profile, period, summary) {
  const key = `receipt_${profile.gstin}_${filingResult.returnType}_${period.year}_${period.month}`;
  const record = {
    arn: filingResult.arn,
    returnType: filingResult.returnType,
    filedAt: filingResult.filedAt,
    period,
    summary,
    gstin: profile.gstin,
    tradeName: profile.tradeName,
  };
  await AsyncStorage.setItem(key, JSON.stringify(record));
  return record;
}

export async function getFilingHistory(gstin) {
  const keys = await AsyncStorage.getAllKeys();
  const receiptKeys = keys.filter(k => k.startsWith(`receipt_${gstin}_`));
  const records = await AsyncStorage.multiGet(receiptKeys);
  return records.map(([, v]) => JSON.parse(v)).sort((a, b) => new Date(b.filedAt) - new Date(a.filedAt));
}

// ─────────────────────────────────────────────
// Main agent entry point
// ─────────────────────────────────────────────

export async function runNotificationAgent({ filingResult, profile, period, summary, returnType, driveAccessToken }) {
  const results = { push: null, drive: null, local: null, reminder: null };

  // 1. Save local record first (always — offline safety)
  try {
    results.local = await saveLocalRecord(filingResult, profile, period, summary);
  } catch (err) {
    results.localError = err.message;
  }

  // 2. Send immediate push notification
  try {
    await sendPushNotification(
      `${returnType} filed ✓`,
      `ARN: ${filingResult.arn} · ${period.label}`,
      { screen: 'Receipt', arn: filingResult.arn }
    );
    results.push = { ok: true };
  } catch (err) {
    results.push = { ok: false, error: err.message };
  }

  // 3. Save to Google Drive if token available
  if (driveAccessToken) {
    const drive = getDriveService(driveAccessToken);
    const htmlContent = buildReceiptHTML(filingResult, profile, period, summary);
    const fileName = `${profile.gstin}_${returnType}_${period.year}_${String(period.month).padStart(2, '0')}_ARN_${filingResult.arn}.html`;

    results.drive = await saveToGoogleDrive(fileName, htmlContent, 'text/html', drive);

    // Also save the raw payload JSON for audit
    const payloadFileName = `${profile.gstin}_${returnType}_${period.year}_${String(period.month).padStart(2, '0')}_payload.json`;
    await saveToGoogleDrive(payloadFileName, JSON.stringify(filingResult.acknowledgement, null, 2), 'application/json', drive);
  } else {
    results.drive = { ok: false, skipped: true, message: 'Google Drive not connected — receipt saved locally only.' };
  }

  // 4. Schedule next period reminder
  try {
    const nextPeriod = { ...period, month: period.month === 12 ? 1 : period.month + 1, year: period.month === 12 ? period.year + 1 : period.year };
    const reminderId = await scheduleDueDateReminder(returnType, nextPeriod, profile.filingFrequency);
    results.reminder = { ok: true, reminderId, nextPeriod };
  } catch (err) {
    results.reminder = { ok: false, error: err.message };
  }

  return {
    ok: true,
    arn: filingResult.arn,
    results,
    message: `Filing complete. ARN ${filingResult.arn} saved${results.drive?.ok ? ' to Google Drive and' : ''} locally.`,
  };
}
